### ISSUE TITLE
Does this support a remote tracking server?

### ISSUE THREAD

**Issue by DoktorMike** [rejuvyesh/MLFlowLogger.jl#2]
I use a remote tracking server running on a different machine connected to an S3 bucket. Can we specify that in your package?

**Comment by rejuvyesh** [comment]
I use it on Azure where I define the `MLFLOW_TRACKING_URI` to point to the remote tracking server. Also it's mostly a wrapper around the `python` MLFlow client, so same setup should work here and feel free to ask if you run into any issues.

**Comment by rejuvyesh** [comment]
Also you can pass the `tracking_uri` as a keyword argument: https://github.com/rejuvyesh/MLFlowLogger.jl/blob/master/src/MLFlowLogger.jl#L37

**Comment by DoktorMike** [comment]
> Also you can pass the `tracking_uri` as a keyword argument: https://github.com/rejuvyesh/MLFlowLogger.jl/blob/master/src/MLFlowLogger.jl#L37

Awesome.
